simple_blog/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns =[
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout')
]

simple_blog/articles/urls.py
from django.urls import path
from . import views


app_name = 'articles'

urlpatterns = [
    path('', views.article_list, name='list'),
    path('create/', views.article_create, name='create'),
    path('<slug:slug_take>', views.article_detail, name='detail'),
]

simple_blog/djangonautic/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static
from articles import views as article_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
    path('about/',views.about),
    path('',article_views.article_list, name='home')
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

simple_blog/accounts/models.py
from django.db import models

# Create your models here.

simple_blog/articles/models.py
from django.db import models
from django.contrib.auth.models import User

class Article(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(default='default.jpeg', blank=True)
    author = models.ForeignKey(User, default=None, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:50]+'...'

simple_blog/articles/forms.py
from django import forms
from .models import Article

class CreateArticle(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['title', 'slug', 'body', 'thumb']

simple_blog/accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('articles:list')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.html', {'form': form})

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('articles:list')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'form': form})


def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('articles:list')

simple_blog/articles/views.py
from django.shortcuts import render, redirect
from .models import Article
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from .forms import CreateArticle

def article_list(request):
    articles = Article.objects.all().order_by('-date')
    return render(request,'articles/article_list.html',{'articles': articles})


def article_detail(request,slug_take):
    article = Article.objects.get(slug=slug_take)
    return render(request, 'articles/article_detail.html', {'article' : article})

@login_required(login_url='/accounts/login/')
def article_create(request):
    if request.method =='POST':
        form = CreateArticle(request.POST, request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            return redirect('articles:list')
    else:
        form = CreateArticle()
    return render(request, 'articles/article_create.html', {'form': form})

simple_blog/djangonautic/views.py
from django.http import HttpResponse
from django.shortcuts import render

def about(request):
    return render(request,'about.html')        #ignore manin one i.e. templates

def homapage(request):
    return render(request,'homepage.html')

simple_blog/accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1> hello Login </h1>
    <form class="site-form" action="{% url 'accounts:login' %}" method="post">
        {% csrf_token %}
        {{ form }}
        {% if request.GET.next %}
            <input type="hidden" name="next" value="{{request.GET.next}}">
        {% endif %}
        <input type="submit" value="Login">
    </form>

{% endblock %}

simple_blog/accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1> hello sign up</h1>
    <form class="site-form" action="/accounts/signup/" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Signup">
    </form>

{% endblock %}

simple_blog/articles/templates/articles/article_create.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="create-article">
    <h2>Lets create an awesome article.</h2>
    <form class="site-form" action="{% url 'articles:create' %} " method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="create">
    </form>
</div>
<script src="/static/slugify.js"></script>
{% endblock %}

simple_blog/articles/templates/articles/article_detail.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="article-detail">
    <div class="article">
        <img src="{{ article.thumb.url }}" alt="">
        <h2>{{ article.title }}</h2>
        <p class="article-para"> {{article.date}}</p>
        <p class="article-para"> {{article.body}}</p>
    </div>
</div>



{% endblock %}

simple_blog/articles/templates/articles/article_list.html
{% extends 'base_layout.html' %}
{% block content %}
    <h1> Articles list </h1>
    <div class="articles">
        {% for article in articles %}
            <div class="article">
                <h2> <a href="{% url 'articles:detail' article.slug %}"> {{article.title}} </a> </h2>
                <p> {{ article.snippet}} </p>
                <p> {{ article.date}} </p>
                <p class="author"> added by {{article.author.username }} </p>
            </div>
        {% endfor %}
    </div>

{% endblock %}

simple_blog/templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>About</title>

</head>
<body>
    <h1> This is About. </h1>
    <p> We like Django </p>
</body>
</html>

simple_blog/templates/base_layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
     <link href="{% static 'css/styles.css' %}" rel="stylesheet">
</head>
<body>

    <header class="wrapper">
        <h1> <a href="{% url 'home' %}"> <img src='{% static "css/logo.png" %}' width="120" alt=""></a> </h1>
        <nav>
            <ul>
                {% if user.is_authenticated %}
                    <li>
                        <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                            {% csrf_token %}
                            <button type="submit">Logout</button>
                        </form>
                    </li>
                    <li><a href="{% url 'articles:create' %}" class="highlight">New Article</a></li>
                {% else %}
                    <li><a href="{% url 'accounts:login' %}">Login</a></li>
                    <li><a href="{% url 'accounts:signup' %}">Signup</a></li>
                {% endif %}
            </ul>
        </nav>
    </header>

    <div class="wrapper">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

simple_blog/templates/homepage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Homepage</title>
</head>
<body>
    <h1> This is Homepage. </h1>
    <p> Welcome to Djangonautic </p>
</body>
</html>